services:
  api:
    build:
      context: ./flask-api
      dockerfile: Dockerfile.api
    image: schedulion-api
    ports:
      - "5000:5000"
  client:
    build:
      context: ./schedulion-react-fe
      dockerfile: Dockerfile.client
    image: schedulion-client
    ports:
      - "3000:3000"
