services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    image: schedulion-api
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    image: schedulion-client
    ports:
      - "3000:3000"
